server:
  port: 18761
#单节点
#应用名称及验证账号
spring: 
  application: 
    name: eureka
  security:
    user:
      name: root
      password: root
eureka:
  instance:
    hostname: eureka
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://root:${spring.security.user.password}@localhost:${server.port}/eureka/
  server:
    #关闭自我保护
    enable-self-preservation: false
    #清理间隔时间
    eviction-interval-timer-in-ms: 5000



