#服务端口
server:
  port: 9002
#应用名称及验证账号
spring:
  application:
    name: service-consumer
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      # host 配置 ip映射
      defaultZone: http://root:root@eureka-server:18761/eureka/
  instance:
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1
    hostname: localhost
    instance-id: service-consumer

feign:
  #开启feignhystrix
  hystrix:
    enabled: true